# Variant calling workflow for testing CWL converstion.
# Start with a basic workflow to expand with additional support
# for things like alignment splitting, disambiguation, variant
# and SV calling.
---
details:
  - algorithm:
      variantcaller: [freebayes, vardict]
      tools_off: [gemini]
      nomap_split_size: 50
      nomap_split_targets: 100
      variant_regions: variant_regions-bam.bed
    analysis: variant2
    genome_build: hg19
